"""Criação da tabela de musicas

Revision ID: 0500800119da
Revises: ff2946fc8ddd
Create Date: 2026-07-08 07:56:23.080114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0500800119da'
down_revision: Union[str, Sequence[str], None] = 'ff2946fc8ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('artista', sa.String(), nullable=True),
    sa.Column('tom', sa.String(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('duracao', sa.String(), nullable=True),
    sa.Column('banda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musicas_id'), 'musicas', ['id'], unique=False)
    op.create_index(op.f('ix_musicas_nome'), 'musicas', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musicas_nome'), table_name='musicas')
    op.drop_index(op.f('ix_musicas_id'), table_name='musicas')
    op.drop_table('musicas')
    # ### end Alembic commands ###
