"""Criacao da tabela de ensaios

Revision ID: 324f639da473
Revises: 0500800119da
Create Date: 2026-07-08 08:10:46.365818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324f639da473'
down_revision: Union[str, Sequence[str], None] = '0500800119da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensaios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('banda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ensaios_id'), 'ensaios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ensaios_id'), table_name='ensaios')
    op.drop_table('ensaios')
    # ### end Alembic commands ###
