"""Iniciando BD

Revision ID: ab6805db114c
Revises: 
Create Date: 2026-07-08 12:48:34.414431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6805db114c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandas_id'), 'bandas', ['id'], unique=False)
    op.create_index(op.f('ix_bandas_nome'), 'bandas', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('ensaios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('banda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ensaios_id'), 'ensaios', ['id'], unique=False)
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('banda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_categoria'), 'equipamentos', ['categoria'], unique=False)
    op.create_index(op.f('ix_equipamentos_id'), 'equipamentos', ['id'], unique=False)
    op.create_table('integrantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('banda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrantes_id'), 'integrantes', ['id'], unique=False)
    op.create_table('musicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('artista', sa.String(length=100), nullable=True),
    sa.Column('tom', sa.String(length=50), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('banda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musicas_id'), 'musicas', ['id'], unique=False)
    op.create_index(op.f('ix_musicas_nome'), 'musicas', ['nome'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('banda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_id'), 'shows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_id'), table_name='shows')
    op.drop_table('shows')
    op.drop_index(op.f('ix_musicas_nome'), table_name='musicas')
    op.drop_index(op.f('ix_musicas_id'), table_name='musicas')
    op.drop_table('musicas')
    op.drop_index(op.f('ix_integrantes_id'), table_name='integrantes')
    op.drop_table('integrantes')
    op.drop_index(op.f('ix_equipamentos_id'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_categoria'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_ensaios_id'), table_name='ensaios')
    op.drop_table('ensaios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_bandas_nome'), table_name='bandas')
    op.drop_index(op.f('ix_bandas_id'), table_name='bandas')
    op.drop_table('bandas')
    # ### end Alembic commands ###
