"""asd

Revision ID: c4ed281f1b4f
Revises: d6708248f6c2
Create Date: 2026-07-09 14:16:35.970987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ed281f1b4f'
down_revision: Union[str, Sequence[str], None] = 'd6708248f6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrantes', sa.Column('papel', sa.String(length=50), nullable=True))
    op.alter_column('integrantes', 'funcao',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integrantes', 'funcao',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('integrantes', 'papel')
    # ### end Alembic commands ###
