"""criando_tabela_financeiro

Revision ID: d6708248f6c2
Revises: 8db935c78120
Create Date: 2026-07-08 19:57:37.918619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6708248f6c2'
down_revision: Union[str, Sequence[str], None] = '8db935c78120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipotransacao'), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('banda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financeiro_id'), 'financeiro', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financeiro_id'), table_name='financeiro')
    op.drop_table('financeiro')
    # ### end Alembic commands ###
