"""criando tabela de usuarios e bandas

Revision ID: ff2946fc8ddd
Revises: 4deae771b8a2
Create Date: 2026-07-07 13:35:41.422319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2946fc8ddd'
down_revision: Union[str, Sequence[str], None] = '4deae771b8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandas_id'), 'bandas', ['id'], unique=False)
    op.create_index(op.f('ix_bandas_nome'), 'bandas', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('integrantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('banda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banda_id'], ['bandas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrantes_id'), 'integrantes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrantes_id'), table_name='integrantes')
    op.drop_table('integrantes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_bandas_nome'), table_name='bandas')
    op.drop_index(op.f('ix_bandas_id'), table_name='bandas')
    op.drop_table('bandas')
    # ### end Alembic commands ###
